export const CATEGORIES = [
  { id: `recommended`, label: 'Recommandations' },
  { id: `tools`, label: 'Outils et utilitaires' },
  { id: `games`, label: 'Jeux' },
];

export const PWAs = [
  // Recommandations --------------------------------------
  {
    icon: `gtaradios`,
    name: `GTA Radios`,
    desc: `Musique`,
    category: `recommended`,
    link: `https://laz-r.github.io/gta-radios-beta/`,
    state: `available`,
  },
  {
    icon: `dinosaurs`,
    name: `Dinosaurs`,
    desc: `Pédagogique`,
    category: `recommended`,
    link: `https://laz-r.github.io/dinosaurs/`,
    state: `available`,
  },
  {
    icon: `3615`,
    name: `3615 Blagues`,
    desc: `Humour`,
    category: `recommended`,
    link: `https://laz-r.github.io/3615-blagues/`,
    state: `available`,
  },

  // Outils et utilitaires --------------------------------
  {
    icon: `convertisseur`,
    name: `Switch it !`,
    desc: `Convertisseur`,
    category: `tools`,
    link: `https://laz-r.github.io/switch-it/`,
    state: `available`,
  },
  {
    icon: `geochronologia`,
    name: `Géochronologia`,
    desc: `Pédagogique`,
    category: `tools`,
    link: `https://laz-r.github.io/geochronologia/`,
    state: `available`,
  },
  {
    icon: `colorhelper`,
    name: `Color Helper`,
    desc: `Assistant colorimétrique`,
    category: `tools`,
    link: `https://laz-r.github.io/color-helper/`,
    state: `available`,
  },
  {
    icon: `vshelper`,
    name: `Viewport-size Helper`,
    desc: `Outil`,
    category: `tools`,
    link: `https://laz-r.github.io/viewport-size-helper/`,
    state: `available`,
  },
  {
    icon: `favorits`,
    name: `Favorits`,
    desc: `Gestion`,
    category: `tools`,
    link: `https://laz-r.github.io/favorits/`,
    state: `available`,
  },
  {
    icon: `monochrono`,
    name: `Mono Chrono`,
    desc: `Chronomètre`,
    category: `tools`,
    link: `https://laz-r.github.io/mono-chrono/`,
    state: `available`,
  },
  {
    icon: `sleepwave`,
    name: `Sleepwave`,
    desc: `Musique`,
    category: `tools`,
    link: `https://laz-r.github.io/sleepwave-dev/`,
    state: `available`,
  },
  {
    icon: `tmnt`,
    name: `Tortues Ninja Punchlines`,
    desc: `Collection`,
    category: `tools`,
    link: `https://laz-r.github.io/tortues-ninja-punchlines/`,
    state: `limited`,
  },
  {
    icon: `knus`,
    name: `Kitchen Nightmare (US)`,
    desc: `Collection`,
    category: `tools`,
    link: `https://laz-r.github.io/kn-us/`,
    state: `limited`,
  },
  
  // Jeux -------------------------------------------------
  {
    icon: `bingo`,
    name: `Bingo: Forces de l'Ordre`,
    desc: `Bingo`,
    category: `games`,
    link: `https://laz-r.github.io/bingo-dev/`,
    state: `available`,
  },
  {
    icon: `soehelper`,
    name: `Shadows of Evil Helper`,
    desc: `Assistant`,
    category: `games`,
    link: `https://laz-r.github.io/soe-helper/`,
    state: `available`,
  },
  {
    icon: `yams`,
    name: `Yams (spécial Matthieu)`,
    desc: `Assistant`,
    category: `games`,
    link: `https://laz-r.github.io/yams-matthieu/`,
    state: `available`,
  },
  {
    icon: `taptaptap`,
    name: `Tap Tap Tap`,
    desc: `Clicker`,
    category: `games`,
    link: `https://laz-r.github.io/taptaptap/`,
    state: `available`,
  },
  {
    icon: `animalquiz`,
    name: `Quiz Animaux`,
    desc: `Quiz`,
    category: `games`,
    link: `https://laz-r.github.io/animal-quizz-test/`,
    state: `limited`,
  },
  {
    icon: `hermes`,
    name: `Mission Hermès`,
    desc: `Colonisation spatiale`,
    category: `games`,
    link: `https://laz-r.github.io/mission-hermes-dev-2/`,
    state: `unavailable`,
  },
  {
    icon: `laramidia`,
    name: `Laramidia 3000`,
    desc: `Aventure`,
    category: `games`,
    link: `https://laz-r.github.io/laramidia-3000-dev/`,
    state: `unavailable`,
  },
  {
    icon: `pkrnd`,
    name: `PKRND`,
    desc: `Combat`,
    category: `games`,
    link: `https://laz-r.github.io/pkrnd/`,
    state: `unavailable`,
  },
  {
    icon: `battles`,
    name: `Battles`,
    desc: `Combat`,
    category: `games`,
    link: `https://laz-r.github.io/battles-dev/`,
    state: `unavailable`,
  },
];

